### ISSUE TITLE
Éviter / supprimer les diacritiques (accents etc) dans les urls

### ISSUE THREAD

**Issue by thbar** [etalab/transport-profil-netex-fr#102]
Un échange sur zoom montre que l'accent est tronqué par zoom, et ça peut arriver avec d'autres outils.

![CleanShot 2024-06-13 at 11 22 26@2x](https://github.com/etalab/transport-profil-netex-fr/assets/10141/6ff706e5-62d6-4071-8c59-c73fabb3057a)

Je recommande qu'on évite les accents dans les urls (mais il faudra gérer une redirection pour ne pas casser l'url précédente, idéalement).

**Comment by TuThoThai** [comment]
Je plussoie la demande de simplifier le lien en évitant les caractères accentués. Cela me facilitera la création de certains documents !

**Comment by thbar** [comment]
Oldie but goodie: https://youtu.be/K4TKJwvTu50?si=i_JJWr16HcusCFzR&t=41

> But if it's possible to avoid special characters in URLs, I would recommend doing that

**Comment by thbar** [comment]
Pour info @ptitfred !

**Comment by TuThoThai** [comment]
@thbar et @ptitfred, je relance le sujet, je suis désolée.
Vu qu'on commence à avoir de plus en plus de GTs sur les données d'accessibilité et des actions de com' NeTEx accessibilité, est-ce faisable dans les semaines à venir ? 🙏

**Comment by ptitfred** [comment]
Je m'en occupe.

**Comment by thbar** [comment]
@ptitfred a géré (pas encore déployé), je viens de voir ça. @TuThoThai on peut en addition du renommage faire éventuellement une redirection (pour garder la stabilité avec l'ancienne url), est-ce que ça te paraît nécessaire au vu des diffusions que tu as pu faire ?

**Comment by TuThoThai** [comment]
@thbar, je te confirme le besoin de faire une redirection (pour le moment). On mettra à jour les supports de com' avec le nouveau lien dès que dispo. Mais ça prendra un peu de temps pour de la propagation naturelle.

**Comment by ptitfred** [comment]
Je m'en occupe

**Comment by TuThoThai** [comment]
Un énorme merci @ptitfred !
