### ISSUE TITLE
"merge" des PRs accessibilité approuvées par le GT7 

### ISSUE THREAD

**Issue by thbar** [etalab/transport-profil-netex-fr#103]
Je re-pointe ici la liste de toutes les PR accessibilité (contributions de @nlehuby qu'on remercie), qui ont été validées d'un point de vue métier par le GT7 (merci @TuThoThai qui a approuvé ces PRs individuellement pour le compte du GT7), de façon à vérifier le rendu final après coup, et m'assurer qu'il n'y a pas de conflits non plus:

### Merge puis vérification du rendu

- [ ] https://github.com/etalab/transport-profil-netex-fr/pull/26
- [ ] https://github.com/etalab/transport-profil-netex-fr/pull/89
- [ ] https://github.com/etalab/transport-profil-netex-fr/pull/90
- [ ] https://github.com/etalab/transport-profil-netex-fr/pull/91
- [ ] https://github.com/etalab/transport-profil-netex-fr/pull/92
- [ ] https://github.com/etalab/transport-profil-netex-fr/pull/93
- [ ] https://github.com/etalab/transport-profil-netex-fr/pull/94
- [ ] https://github.com/etalab/transport-profil-netex-fr/pull/95
- [ ] https://github.com/etalab/transport-profil-netex-fr/pull/96
- [ ] https://github.com/etalab/transport-profil-netex-fr/pull/97

**Comment by thbar** [comment]
@TuThoThai @nlehuby j'ai pu merger jusqu'à #95 inclus, puis sur #96 il apparaît qu'il y a un conflit qui empêche le merge.

Je vais regarder de plus près si le conflit est trivial ou pas.

**Comment by thbar** [comment]
Vu que c'est un fork, il est moins évident de voir d'où ça vient. @nlehuby pourras-tu jeter un oeil ? Merci !

**Comment by nlehuby** [comment]
j'ai fait un rebase et résolu le conflit, ça devrait être bon.

**Comment by thbar** [comment]
Merci @nlehuby !

Je garde ouvert pour aller jeter un oeil sur le site avant de clôturer.

**Comment by thbar** [comment]
Tout est bon, par contre j'ai créé le ticket suivant:
- #104 

qu'il va falloir traiter.
