### ISSUE TITLE
Documentation à capturer : correspondances avec CNIG & OSM

### ISSUE THREAD

**Issue by thbar** [etalab/transport-profil-netex-fr#107]
Je capture ici des informations partagées par Muriel Larrouy (et déjà évoquées précédemment par @TuThoThai), en me disant que ça pourra faire partie d'une FAQ ici.

Objectif : réduire la double saisie, travailler sur les correspondances entre CNIG / Acceslibre mobilité etc.

- règles de conversion CNIG NeTEx https://www.ecologie.gouv.fr/sites/default/files/documents/Wegoto_DGMINT_ReglesConversions_CNIG-NeTEx_0.9.pdf
- règles de conversion OSM NeTEx
https://www.ecologie.gouv.fr/sites/default/files/documents/JungleBus_AccesLibreMobilites_ReglesConversion_OSM-NeTEx_1.0.pdf
- La dernière version du standard du CNIG est disponible
https://cnig.gouv.fr/IMG/pdf/240215_standard_cnig_accessibilite_v2021-10_rev2024-02.pdf

**Comment by nlehuby** [comment]
pour info, j'ai déjà ajouté ces liens dans la partie "Bibliographie" du profil accessibilité, tout à la fin.

**Comment by thbar** [comment]
@nlehuby ahh superbe, merci ! Je vais linker ça dans une issue "FAQ", mais du coup je pense qu'on peut fermer pour le moment. Merci !

**Comment by GT-CNIG-DDU** [comment]
Le lien permanent vers le standard CNIG Accessibilité est : https://cnig.gouv.fr/ressources-accessibilite-a25335.html
(car le lien direct au pdf change avec les versions du standard)

**Comment by thbar** [comment]
@GT-CNIG-DDU merci ! Je vais reporter sur #108.
