### ISSUE TITLE
Valeurs pour FuelType

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-profil-netex-fr#6]
Actuellement les valeurs de `TypeOfFuel` sont les suivantes

- petrol : essence
- diesel: diesel
- naturalGas : gaz
- biodiesel : diesel bio
- electricity : électrique
- other : autre

La spécification [GTFS Vehicles](https://docs.google.com/document/d/156RiBjI6FnWJvO8_XWX11Q9nLdOiBdS_rilA-oamlv8/edit) définit d'autres valeurs, permettant une granularité différente.

1 - Gasoline
2 - Diesel
3 - Natural gas
4 - Diesel-electric hybrid
5 - Natural gas hybrid
6 - Battery electric
7 - Fuel cell
8 - Hydrogen

Cet énuméré est-il figé ? Est-il envisagé de revoir/ajouter des valeurs ?

**Comment by Aurige** [comment]
Cette liste est celle des profils France. Vous pouvez faire un PR si vou souhaitez qu'elle soit complétée.

La liste complète dand NeTEx est :
1.  battery 
2.  biodiesel 
3.  diesel 
4.  dieselBatteryHybrid 
5.  electricContact 
6.  electricity 
7.  ethanol 
8.  hydrogen 
9.  liquidGas 
10.  tpg 
11.  methane 
12.  naturalGas 
13.  petrol 
14.  petrolBatteryHybrid 
15.  petrolLeaded 
16.  petrolUnleaded 
17.  none 
18.  other 

et un type ouvert permet aussi de l'étendre si nécessaire.

**Comment by TuThoThai** [comment]
PR à préparer pour avaliser le changement lors de la prochaine plénière du GT7 le 21 novembre 2024.
@prhod, @albanpeignier et @Aurige : ok pour vous ? Si oui, je prépare la PR.

**Comment by prhod** [comment]
Ok pour moi. A la première lecture, je me demande pourquoi avoir restreint la liste dans le profil FR. Y a-t-il une contre indication à laisser la liste complète si c'est simplement un enum ?

**Comment by TuThoThai** [comment]
Accord pour ajout des éléments de l'enum dans la v2.3 du profil France de NeTEx.
PR à préparer par moi-même.
