### ISSUE TITLE
Retranscription "Profil Parking" en Markdown

### ISSUE THREAD

**Issue by thbar** [etalab/transport-profil-netex-fr#62]
Le profil parking NeTEx m'a été communiqué par @Aurige. C'est un profil validé par la CN03.

Si j'ai compris (à confirmer) il va être à intégrer directement ici, comme sous-partie du profil NeTEx France.

C'est un document Word qu'il faudra retranscrire.

Je crée le ticket, et un de mes collègues va se lancer dessus (poke @vdegove), je lui transmettrai le mode opératoire utilisé pour la dernière retranscription.

@Aurige question complémentaire : combien de documents reste-t-il à intégrer, hormis celui-ci ? Je cherche à évaluer la charge de notre côté en termes de retranscription, et aussi à faire figurer ça sur le projet GitHub.

EDIT @thbar: le lien vers le doc est ici sauf erreur:
- https://github.com/etalab/transport-normes/files/14095152/NF_Profil.NeTEx.pour.les.Parkings.F.-.v1.2a.docx

**Comment by Aurige** [comment]
A priori, il ne reste plus que le Profil Tarif ...

**Comment by thbar** [comment]
@Aurige ça marche merci ! Est-ce un gros document ? (pour évaluer la charge).

Poke @TuThoThai pour qu'on crée un ticket spécifique !

**Comment by Aurige** [comment]
Le voila [NF_Profil NeTEx pour les Tarifs(F) - v1.3.docx](https://github.com/etalab/transport-normes/files/14087618/NF_Profil.NeTEx.pour.les.Tarifs.F.-.v1.3.docx)

**Comment by thbar** [comment]
@Aurige merci ! C'est stabilisé ça ne vit plus trop ? Pour savoir comment le caler. Quelle est la priorité relative de parking vs tarifs aussi, histoire que je ne me trompe pas là dessus ?

**Comment by Aurige** [comment]
ça ne bouge pas en ce moment ... on aura une mise à jour à faire une fois le profil Tarif EU fini (travaux en cours) ... mais pas avant 1 an

**Comment by TuThoThai** [comment]
@thbar et @Aurige 
Pour simplifier les tickets, je remets celui du Profil Tarif dans une autre discussion. 😉

**Comment by Aurige** [comment]
C'est le moins urgent vu la maturité du domaine (personne n'a encore d'outil... même avec des formats de sortie non normés)
Par contre, comme pour tout le reste, à un moment ça va être ultra urgent ;-)

**Comment by thbar** [comment]
> @thbar et @Aurige
> Pour simplifier les tickets, je remets celui du Profil Tarif dans une autre discussion. 😉

Parfait !

> Par contre, comme pour tout le reste, à un moment ça va être ultra urgent ;-)

Clairement d'accord, c'est pour ordonnancer à court terme le travail dessus. Merci, c'est utile !

**Comment by thbar** [comment]
@TuThoThai je te laisse attacher la PJ du parking ici, on la linkera directement dans la description tout en haut, car on va bosser dessus à plusieurs collègues. Merci !

**Comment by TuThoThai** [comment]
@thbar Et voici ! Un grand merci à toute l'équipe pour le soutien apporté à la publication des profils français de NeTEx.
[NF_Profil NeTEx pour les Parkings(F) - v1.2a.docx](https://github.com/etalab/transport-normes/files/14095152/NF_Profil.NeTEx.pour.les.Parkings.F.-.v1.2a.docx)

**Comment by thbar** [comment]
Attention @TuThoThai Word me remonte la présence de macros dans le profil parking, il faudra vérifier si c'est problématique (sécurité) ou pas.

**Comment by thbar** [comment]
> Attention @TuThoThai Word me remonte la présence de macros dans le profil parking, il faudra vérifier si c'est problématique (sécurité) ou pas.

Pour être précis: je ne parle pas de ce que tu as linké (on s'est croisés) mais de ce que Christophe avait partagé par mail.

**Comment by thbar** [comment]
Terminé (voir #87), on peut clôturer !
