### ISSUE TITLE
Retranscription NeTEx "Profil Tarif" en markdown pour publication

### ISSUE THREAD

**Issue by TuThoThai** [etalab/transport-profil-netex-fr#63]
Le voila [NF_Profil NeTEx pour les Tarifs(F) - v1.3.docx](https://github.com/etalab/transport-normes/files/14087618/NF_Profil.NeTEx.pour.les.Tarifs.F.-.v1.3.docx)

_Originally posted by @Aurige in https://github.com/etalab/transport-normes/issues/62#issuecomment-1915221051_
            

Edit @thbar - je remets le lien communiqué par @Aurige directement dans l'issue ici:

- https://github.com/etalab/transport-normes/files/14087618/NF_Profil.NeTEx.pour.les.Tarifs.F.-.v1.3.docx

**Comment by TuThoThai** [comment]
@thbar & @Aurige, merci de reprendre la discussion tarif ici -- si besoin

**Comment by thbar** [comment]
Deux questions se posent :

1. Nous (transport.data.gouv.fr) sommes régulièrement sollicités pour nous demander où est ce "profil tarif". Or, la transposition en markdown va prendre du temps. Peut-on envisager simplement que quelqu'un me communique la version PDF (idéalement, pas de DOCX, pour éviter des modifications trop triviales) et que je la publie sur https://normes.transport.data.gouv.fr avec une note explicative ?

=> je crée un ticket séparément

2. Qui va se charger de cette transposition en markdown ? C'est un travail non négligeable (et idem pour le profil parking), il faudrait fixer ça maintenant que l'outillage est à peu près en place.

**Comment by thbar** [comment]
Le traitement a été réalisé en deux temps:
- Un quick-fix en PDF ici https://github.com/etalab/transport-profil-netex-fr/issues/71
- La retranscription (merci @ptitfred) ici https://github.com/etalab/transport-profil-netex-fr/pull/84

Le tout a été validé (https://github.com/etalab/transport-profil-netex-fr/pull/84#issuecomment-2147625302) par le GT7 et est à présent disponible sur le web (https://normes.transport.data.gouv.fr/normes/netex/tarifs/).

Merci à tous !
