### ISSUE TITLE
Proposition de renommage du repository actuel (puis renommage à faire)

### ISSUE THREAD

**Issue by thbar** [etalab/transport-profil-netex-fr#69]
Hello,

Poke @TuThoThai, @Aurige, @Henault, @albanpeignier en particulier.

J'ai du l'évoquer mais je ne retrouve pas de trace écrite, aussi je le mets ici, ce n'est pas plus mal.

Je propose de:
- renommer ce repository qui s'appelle actuellement `transport-normes`, à terme, en `transport-profil-netex-fr` (et j'en effacerai à terme le contenu "SIRI")
- de créer à côté `transport-profil-siri-fr` (voir https://github.com/etalab/transport-normes/issues/65)

Est-ce que ce nommage vous convient ?

Merci !

**Comment by TuThoThai** [comment]
Hello @thbar !

Les noms sont bien ceux que nous avons proposé lors de notre session de travail pour la publication des profils de normes. Je les soumets à validation officielle pour la prochaine plénière du GT7 le 4 avril.
Je ne vois pas d'objection à venir des membres du GT7. Tu peux donc "préparer" les repos sur la base du nommage proposé.

Merci !

**Comment by thbar** [comment]
Le renommage a été fait.
