### ISSUE TITLE
Publier le profil "tarif" en PDF dès que possible

### ISSUE THREAD

**Issue by thbar** [etalab/transport-profil-netex-fr#71]
Le PAN est régulièrement sollicité au sujet de ce profil.

Pour ne pas bloquer la publication du fait de la nécessité suivante:
- #63 

le PAN propose de publier la dernière version validée en format PDF.

Je peux me charger de cette publication, si un autre membre du GT7 peut faire un export "officiel" en PDF en étant sûr de la version exportée, et l'attacher ici.

De cette façon je créerai une section spécifique sur le site avec le document en lien, et une notice explicative, et tout le monde sera content :smile: (utile pour avancer sur des chantiers qui impliquent ce profil).

**Comment by thbar** [comment]
Poke @TuThoThai @Aurige @Henault en particulier !

**Comment by thbar** [comment]
@TuThoThai pour le tarif plutôt à coller ici s'il te plaît !

**Comment by TuThoThai** [comment]
De ce que je sais : le profil a été public en décembre 2021 après validation en GT7. Le site de publication est celui de [normes-données-tc.org](http://www.normes-donnees-tc.org/profils/)

@Aurige pourra confirmer

**Comment by thbar** [comment]
La publication a été faite via #75.
