### ISSUE TITLE
Publier le profil "parking" en PDF dès que possible

### ISSUE THREAD

**Issue by thbar** [etalab/transport-profil-netex-fr#72]
Voir:
- #71 
- #63 
- #62 

Dans la même idée, si quelqu'un du GT7 autre que moi peut réaliser un export fiable et autoritatif en PDF et l'attacher ici, je me chargerai de le publier sur normes.transport.data.gouv.fr sans + de délai.

Poke @TuThoThai @Aurige @Henault en particulier !

**Comment by Henault** [comment]
Hello
Je peux le faire mais je ne suis pas dépositaire de la version officielle de ces profils …

Envoyé à partir de Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Thibaut Barrère ***@***.***>
Envoyé : Wednesday, March 27, 2024 1:02:15 PM
À : etalab/transport-profil-netex-fr ***@***.***>
Cc : HENAULT Thierry ***@***.***>; Mention ***@***.***>
Objet : [etalab/transport-profil-netex-fr] Publier le profil "parking" en PDF dès que possible (Issue #72)


Voir:

  *   #71<https://github.com/etalab/transport-profil-netex-fr/issues/71>
  *   #63<https://github.com/etalab/transport-profil-netex-fr/issues/63>
  *   #62<https://github.com/etalab/transport-profil-netex-fr/issues/62>

Dans la même idée, si quelqu'un du GT7 autre que moi peut réaliser un export fiable et autoritatif en PDF et l'attacher ici, je me chargerai de le publier sur normes.transport.data.gouv.fr sans + de délai.

Poke @TuThoThai<https://github.com/TuThoThai> @Aurige<https://github.com/Aurige> @Henault<https://github.com/Henault> en particulier !

**Comment by thbar** [comment]
@Henault il serait préférable d'avoir la version officielle via le bon dépositaire, pour éviter tout souci ! Mais merci !

**Comment by TuThoThai** [comment]
@Aurige, pourrais tu m'envoyer la dernière version stable du profil Tarifs ? Je m'occupe des exports pdf en tant qu'animatrice du GT7. Cela donnera à @thbar et l'équipe du PAN la confirmation officielle du contenu. 😃

**Comment by thbar** [comment]
@TuThoThai impeccable, et moi je me chargerai de la publication technique en mode "vite fait" sur le site. Et comme ça on pourra gagner du temps pour la transcription !

**Comment by TuThoThai** [comment]
@thbar 
voici le PDF du profil Parking
[NF_Profil NeTEx pour les Parkings(F) - v1.2a.pdf](https://github.com/etalab/transport-profil-netex-fr/files/14787408/NF_Profil.NeTEx.pour.les.Parkings.F.-.v1.2a.pdf)

**Comment by thbar** [comment]
@TuThoThai @Aurige pouvez-vous préciser la date de publication initiale de ces documents et le processus associé ? C'était en commission ? Je reflèterai cela sur le site.

**Comment by thbar** [comment]
La publication a été faite via #75.
