### ISSUE TITLE
Quelle est la version du "profil NeTEx accessibilité" actuellement en ligne ?

### ISSUE THREAD

**Issue by thbar** [etalab/transport-profil-netex-fr#78]
Une question évoquée entre moi et @gonzalezsuitt aujourd'hui et qui (re) soulève des points très importants : sur https://normes.transport.data.gouv.fr/normes/netex/accessibilité/ il y a le profil accessibilité, la date affichée est 13 janvier 2022.

L'historique est ici: https://github.com/etalab/transport-profil-netex-fr/commits/4093bb60378a37b3c1b8ed7042e3c41f1aad50d3/accessibilité/index.md?browsing_rename_history=true&new_path=NeTEx/accessibilité/index.md&original_branch=main

Les questions que je me pose (et qui s'appliquent en fait à la totalité des pages) sont les suivantes:
- quelle est la version de ce profil ?
- quand a-t-elle été validée par le groupe de travail ?
- est-ce la version la plus récente, et si non, quelle est la bonne version et quelle est la distance à la version affichée actuellement ?

Ces documents commencent à être utilisés dans des contextes d'appel d'offre, il faut mettre d'équerre l'historique dès que possible.

**Comment by thbar** [comment]
@TuThoThai @Aurige qui peut me renseigner sur ce point s'il vous plaît ? La même question va se poser sur tous les profils, avant qu'on aie le temps d'homogénéiser les versions ! Ces infos aideront d'ailleurs à préparer la release.

**Comment by TuThoThai** [comment]
@thbar, voici les infos dont je dispose :

- le profil Accessibilité publié sur le site a bien été confirmé en GT7 en 2022
- courant 2023, des demandes de changements du profil ont eu lieu (cf. PRs de Noémie et discussions lors des deux derniers GT7)
- en janvier 2024 : les changements proposés par Noémie ont été validés en plénière du GT7
- en janvier 2024 : il a été décidé que ces changements seront retranscrits dans le profil une fois le processus de publication utilisant GitHub sera stabilisé

@Aurige, peux-tu confirmer ?

Par contre, je n'ai pas le numéro de version. @Aurige l'a sûrement.

**Comment by prhod** [comment]
Le document référencé sur http://www.normes-donnees-tc.org/category/netex/ indique 2.2 pour le profil Accessibilité

**Comment by thbar** [comment]
Merci @prhod ! Je propose d'incorporer ça dans le CHANGELOG (qu'il faudra créer d'ailleurs) pour #80.

**Comment by thbar** [comment]
Ce point est revenu sur la table aujourd'hui (échanges avec Muriel Larrouy et @TuThoThai), on va en reparler !

**Comment by TuThoThai** [comment]
Note pour la prochaine version (cf. échange d'email avec la la C.F.P.S.A.A.)
> lorsqu'une bande de guidage est implantée, il est obligatoire de renseigner les tronçons de cheminement correspondants. (phrase à écrire en jaune, dans la case TactileGuidingStrip du tableau 11 du [§ cheminements](https://normes.transport.data.gouv.fr/normes/netex/accessibilité/#les-cheminements))."

**Comment by nlehuby** [comment]
Remarque connexe : [Éléments communs](https://normes.transport.data.gouv.fr/normes/netex/elements_communs/#version-du-profil) propose de faire apparaitre le numéro de version de NeTEx et du profil dans PublicationDelivery.
Du coup, je pense qu'on devrait explicitement avoir une phrase dans le texte de chaque profil qui dit "Ce document correspond à la version X.X du profil XX, compatible avec la version XX du XSD NeTEx", pour éviter d'avoir à farfouiller dans le changelog pour trouver l'info.

**Comment by prhod** [comment]
Je pense effectivement qu'il faudrait revoir ce chapitre en fonction du nouveau versionning envisagé pour le profil France. 
Et +1 pour la proposition de référence à la version de la norme sur le profil FR (et donc les différents documents)

**Comment by TuThoThai** [comment]
Je propose de fermer ce ticket et de continuer la discussion sur les références des numéros de version des profils France en lien avec le XSD de NeTEx [ici](https://github.com/etalab/transport-profil-netex-fr/issues/109).
Merci ! 😄
