### ISSUE TITLE
Créer une release NeTEx (après effacement de SIRI dans le repo)

### ISSUE THREAD

**Issue by thbar** [etalab/transport-profil-netex-fr#80]
Il faut préalablement je pense:
- [x] identifier les numéros de version de chaque sous-partie de NeTEx telle qu'actuellement publiée sur le site (voir #78, #79)
- [x] voir si une mise à jour de contenu est nécessaire (le contenu actuellement publié est-il bien le dernier validé en GT ?)
- [x] fixer un numéro de version
- [x] créer un tag/release
- [x] préparer un changelog, a minima sur les releases elles-mêmes, ou bien directement dans un fichier CHANGELOG ou bien les deux, et mentionner les versions "from" (d'où on vient) et "to" la nouvelle "version groupée"
- [ ] puis aller modifier le processus de publication sur le site

**Comment by thbar** [comment]
J'ajoute aux tâches plus haut directement : préparer un changelog, a minima sur les releases elles-mêmes, ou bien directement dans un fichier `CHANGELOG` ou bien les deux.

**Comment by TuThoThai** [comment]
@thbar, je reprends ici le tableau des versions des sous-profils de NeTEx à la suite de la plénière du 13 juin.
|Norme|(Sous-)Profil|Dernière version publiée|Date de validation|Prochaine version|Ouverture des travaux|Présentation des travaux en GT7|
|---|---|---|---|---|---|---|
|NeTEx|Eléments communs|v2.2|Janvier 2021|v2.3|Eté 2024|Septembre 2024|
|NeTEx|Description des arrêts|v2.2|Janvier 2021|v2.3|Eté 2024|Septembre 2024|
|NeTEx|Horaires|v2.2|Janvier 2021|v2.3|Eté 2024|Septembre 2024|
|NeTEx|Description des réseaux|v2.2|Janvier 2021|v2.3|Eté 2024|Septembre 2024|
|NeTEx|Accessibilité|v2.2|Janvier 2021|v2.3|Novembre 2023|Janvier 2024|
|NeTEx|Tarifs|v2.3|Décembre 2021|v2.4|Septembre 2024|1er trimestre 2025|
|NeTEx|Parking|v1.2a|Eté 2024|v1.3|???|???|
|NeTEx|Nouveaux modes|N/A|N/A|v1.0|Janvier 2024|Fin 2024|
|SIRI|France|v1.7|Eté 2023|v1.8|Septembre 2024|1er trimestre 2025|

**Comment by thbar** [comment]
@TuThoThai quand tu écris "Date de validation", c'est la validation de la CN03? Du GT associé? (pas du ministère j'imagine ?) Probablement utile de le spécifier dans le nom de la colonne pour éviter toute ambiguïté. 

Super boulot sinon !

**Comment by prhod** [comment]
@TuThoThai pour les tarifs ce ne serait pas 1.3 au lieu de 2.3 sur la dernière version publiée ?
Si on se dit qu'on aligne tout le monde sur une même version, pourquoi proposer les nouveaux modes en 1.0 et les parkings en 1.3 ? => surtout si on essaie de mettre tout le monde dans le même fichier ZIP avec des éléments communs partagés.
(pardon pour la demande s'il s'agit de points validés en GT7)

**Comment by TuThoThai** [comment]
> @TuThoThai quand tu écris "Date de validation", c'est la validation de la CN03? Du GT associé? (pas du ministère j'imagine ?) Probablement utile de le spécifier dans le nom de la colonne pour éviter toute ambiguïté.

@thbar, je confirme que la date de validation dans le tableau est celle en GT7 puis CN 03. Le tableau a été modifié pour refléter cela.

 > @TuThoThai pour les tarifs ce ne serait pas 1.3 au lieu de 2.3 sur la dernière version publiée ?

@prhod, je confirme la coquille. Merci de l'avoir vue ! 😊

 > Si on se dit qu'on aligne tout le monde sur une même version, pourquoi proposer les nouveaux modes en 1.0 et les parkings en 1.3 ? => surtout si on essaie de mettre tout le monde dans le même fichier ZIP avec des éléments communs partagés.
(pardon pour la demande s'il s'agit de points validés en GT7)

@prhod, je n'ai pas d'avis tranché sur la question et ce ne fut pas discuté. Je vois deux options ici :
- option 1 : remettre les compteurs "à zéro" et décider que tous les sous-profils se collent à la version de NeTEx profil France, soit v2.3
- option 2 : décider que la version de NeTEx profil France est la v2.3 avec des numéros différents pour certains sous-profil

Pour une meilleure lisibilité, je penche très fortement sur l'option 1 mais je me plierai à la majorité. 😁

**Comment by prhod** [comment]
@TuThoThai sur les numéros de versions, on l'avait décrit dans la procédure de gestion des modifications ([lien github](https://github.com/TuThoThai/transport-profil-netex-fr/blob/Process-Publication/Process-Redaction-Modification-Publication.md#gestion-des-sous-profils-de-netex)).
> Dans la mesure où NeTEx a donné lieu à la rédaction de plusieurs sous-profils français (ex. accessibilité, éléments communs, etc.), il a été décidé que tout changement dans un sous-profil entraine un changement de version au niveau 2 pour l’ensemble des autres sous-profils. Cela permettra une prise en main plus aisée du profil français de NeTEx dans son ensemble.

Perso, je pense qu'il est nécessaire d'avoir cette version cohérente pour tous les sous-profils. A dispo si besoin pour en discuter.

**Comment by TuThoThai** [comment]
Ok avec toi @prhod pour une v2.3 pour tous les sou-profils à partir de cet été.

**Comment by TuThoThai** [comment]
Mise à jour à la suite de la plénière GT7 en date du 21 novembre 2024 :
- Toutes les parties (ou sous-profils) du profil France de NeTEx actuellement publiés seront marqués en *v2.3* une fois le informations réglementaires mises à jour.
- Cette version est commune à tous les sous-profils.
- La *prochaine version* du profil France de NeTEx sera la *v2.4*

Un milestone dans ce repo a été créé pour reprendre ces éléments en date du 25 novembre 2024

**Comment by TuThoThai** [comment]
@thbar, je te laisse fermer ce ticket dès qu'on est bon pour la publication sur le site. Merci !

**Comment by thbar** [comment]
Voilà c'est fait, la release https://github.com/etalab/transport-profil-netex-fr/releases/tag/v2.3 a été créée et est affichée sur le site.
