### ISSUE TITLE
Retrouver puis afficher les dates de validation / publication de chaque partie de NeTEx France

### ISSUE THREAD

**Issue by thbar** [etalab/transport-profil-netex-fr#81]
Il va être nécessaire de valider les dates, pour tout un tas de raisons:
- clarté pour le grand public, les réutilisateurs
- aide par rapport aux prestations mises en place par des AOMs (relation contractuelle etc)
- et aussi, précédents qui peuvent être utiles pour d'autres travaux européens

Les dates sont variées:
- date(s) de validation par le ou les groupes ayant travaillé sur le profil (certains profils sont co-écrits par 2 groupes)
- date de validation en CN
- date de publication par le ministère (qui est si j'ai compris légalement "contraignant" car le site est référencé par les décrets)

Il faut donc identifier ces dates pour chaque sous-partie de NeTEx, puis décider de comment afficher ces éléments, et au final implémenter cela sur le site.

**Comment by TuThoThai** [comment]
@Aurige, Emmanuel de Verdalle et moi-même pourront retrouver les éléments pour la partie GT7 et CN 03 (aval sur travaux du GT7).

Par contre, il est fort probable que cela souligne le différentiel temporel entre la validation en GT7, CN03 et la publication sur le site normes.transport.data.gouv.fr des profils confirmés (cf. [PR ](https://github.com/etalab/transport-profil-netex-fr/pull/32)en lien avec SIRI - Profil France v1.7).
Comment s'assurer que tous comprennent que le différentiel temporel est lié aux outils et un manque global de ressources plutôt qu'une mauvaise volonté ?

@Aurige, @thbar : une idée ?

**Comment by Aurige** [comment]
Je peux donner les dates des versions validée avec le GT7 ... pour la CN03, on a eu des pb de compte rendu récurents et on retrouvera difficilement les infos. Par contre c'est systèmatiquement la réunion CN03 après la finalisation par le GT7. Pour la partie ministère, je n'ai clairement pas la main.

1. Profil NeTEx Elements communs - début 2014 - dernière version Mars 2019
2. Profil NeTEx Arrêts - début 2014 - dernière version Nov 2015
3.  Profil NeTEx Réseau- début 2014 - dernière version Mars 2019
4. Profil NeTEx Horaires - début 2014 - dernière version Mars 2015
5. Profil NeTEx Accessibilité - début 2017 - dernière version Dec 2019 + révision en cours ...
6. Profil NeTEx Tarif- début 2019 - dernière version Fev 2021
7. Profil NeTEx Parking - début 2021 - dernière version Oct 2021 mais validation CN03 très décalée

**Comment by thbar** [comment]
Merci - concernant accessibilité ces dates seront citées dans la newsletter de transport.data.gouv.fr qui va partir dans quelques jours !

**Comment by thbar** [comment]
Éléments actualisés par @TuThoThai ici:
- https://github.com/etalab/transport-profil-netex-fr/issues/80#issuecomment-2175507473

Je propose de clarifier sur le site comme suit:
- une date de "publication ministérielle" (qui est la date juridiquement contraignante), date de première publication sur le site
- la date de validation telle que rapportée par @TuThoThai dans le tableau de récapitulatif, à des fins de montrer le processus normatif

Les deux gagneront à être affichées ensemble sur chaque profil, à voir sous quelle présentation.

**Comment by thbar** [comment]
Voir:
- #104 (corrigé dans #106)

**Comment by TuThoThai** [comment]
Affichage fait dans la release note
