### ISSUE TITLE
Création d'une milestone pour la release iso-fonctionnelle

### ISSUE THREAD

**Issue by thbar** [etalab/transport-profil-netex-fr#98]
Il y a actuellement 17 PR ouvertes sur le repository (https://github.com/etalab/transport-profil-netex-fr/pulls).

Pour que ça soit clair, j'aimerais qu'on crée une "milestone" GitHub qui regroupe celles qu'on souhaite intégrer à la prochaine release de NeTEx, qui est supposée être "très iso-fonctionnelle", avec "juste" un numéro de version homogène.

Cela éviterait qu'on se retrouve à merger trop tôt quelque chose qui change le périmètre, et devoir faire un rollback après etc.

@TuThoThai @Aurige @prhod en particulier, qu'en pensez-vous ?

Je peux avec votre accord créer une milestone même sans le numéro de version pour commencer (petit nom à définir), et je propose d'inclure par exemple (à discuter évidemment)
- https://github.com/etalab/transport-profil-netex-fr/issues/88
- https://github.com/etalab/transport-profil-netex-fr/issues/80
- https://github.com/etalab/transport-profil-netex-fr/issues/78
- https://github.com/etalab/transport-profil-netex-fr/issues/68
- https://github.com/etalab/transport-profil-netex-fr/issues/63
- https://github.com/etalab/transport-profil-netex-fr/issues/62

**Comment by Brewennn** [comment]
D'accord avec toi Thibaut.

**Comment by prhod** [comment]
Il est possible que la 88 nous pose des questions pas rapide a répondre. Je suis OK pour la milestone, mais je préfère sans cette issue.

**Comment by TuThoThai** [comment]
D'accord avec @prhod sur le fait que la #88 est pour une milestone ultérieure. Dans le même état d'esprit, j'ai aussi la #101 qui porte sur le contenu du sous-profil Tarifs.

**Comment by TuThoThai** [comment]
@Aurige et @prhod, j'ai construit un [tableau ](https://github.com/etalab/transport-profil-netex-fr/issues/80#issuecomment-2175507473)d'identification de toutes les versions des (sous-)profils que nous avons à ce jour. Je suis basée sur les pdf que j'ai et le site normes-donnes-tc.

Ma proposition à faire valider par tous : "Geler" le profil France de NeTEx (avec tous ses sous-profils) à la v2.3 de cet été.

**Comment by prhod** [comment]
Merci @TuThoThai ! Ok pour caler tous les profils sur une version 2.3.
(j'ai ajouté un commentaire sur ton [tableau](https://github.com/etalab/transport-profil-netex-fr/issues/80#issuecomment-2175507473) )

**Comment by thbar** [comment]
Hello à tous ! Je cherche à faire le point (avant le GT7 du 12 septembre), et j'ai l'impression qu'on est dans un état proche de pouvoir faire une livraison.

Je m'explique:
- https://github.com/etalab/transport-profil-netex-fr/pull/106 a été mergée (merci @TuThoThai pour le contenu et @nlehuby pour la review)
- https://github.com/etalab/transport-profil-netex-fr/issues/104 est traité
- https://github.com/etalab/transport-profil-netex-fr/issues/78 s'est affiné
- les 10 PR de @nlehuby 💪 ont été mergées https://github.com/etalab/transport-profil-netex-fr/issues/103

Il serait utile en amont du GT7 de lister ce qui reste éventuellement à faire (et mettre de côté le reste), pour pouvoir finaliser la version "généralisée" (qu'on fixera pour de bon).

J'aimerais beaucoup qu'on arrive, en ce qui me concerne, à mettre à jour les dates de publication de chaque partie avec "la bonne date", avant de geler la "version finale globale" !

Votre avis ?

**Comment by TuThoThai** [comment]
@thbar, j'ai clos à l'instant le ticket #78 vu qu'on a mis à jour et la version du profil et sa date. J'ai bougé les commentaires annexes dans un autre ticket.

Je propose les étapes suivantes :
- présentation du tableau des versions à l'ensemble du GT7 en plénière le 12 septembre
- aval du GT7 _(a priori)_
- présentation en CN03 à la plénière du 20 septembre
- aval de la CN03 _(a priori)_
- MàJ sur le site et "gel" de la version finale globale.

Les travaux mineurs sur les sous profils (domaine d'application et références LOM) pourront être l'occasion pour vous de faire une release suivante. Ca nous donnera un bon rythme. 😉 

Votre avis ?
